name = "MultivariableFunctions"
uuid = "ef1b8a6c-1cd6-4f7f-a2e8-9c9a3f70b122"
authors = ["Julia Education Team"]
version = "0.1.0"

[deps]

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"] 