name = "Interpolation"
uuid = "c6033557-3d49-4d78-b101-5a4b9c460f5d"
authors = ["Educational Project"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"
Plots = "1.0" 